Scoolfirst.Admin/Controllers/SyllabusDatesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Scoolfirst.Model.Context;
using Scoolfirst.Model.WorkBook;
using Scoolfirst.Admin.Models;
using Scoolfirst.Model.Provider;
using Scoolfirst.Model.MongoDatabase;
using Scoolfirst.Model.Notifications;

namespace Scoolfirst.Admin.Controllers
{
    [Authorize]
    public class SyllabusDatesController : Controller
    {
        private ScoolfirstContext db = new ScoolfirstContext();

        // GET: SyllabusDates
        public ActionResult Index(int page=1,int size=10,string search="")
        {
            IQueryable<SyllabusDate> List;
            if (!string.IsNullOrEmpty(search))
                List = db.SyllabusDates.Where(i => i.Title.Contains(search));
            else
                List = db.SyllabusDates;
            ViewBag.Pager = Pagers.Items(List.Count()).PerPage(size).Move(page).Segment(20).Center();
            return View(List.OrderBy(i=>i.Id).Skip((page-1)*size).Take(size).ToList());
        }

        // GET: SyllabusDates/Details/5
        public ActionResult Details(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SyllabusDate syllabusDate = db.SyllabusDates.Find(id);
            if (syllabusDate == null)
            {
                return HttpNotFound();
            }
            return View(syllabusDate);
        }

        // GET: SyllabusDates/Create
        public ActionResult Create()
        {
            ViewBag.Class = new SelectList(db.Classes, "Id", "RomanDisplay");
            ViewBag.School = new SelectList(db.Schools, "Id", "SchoolName");
            return View();
        }

        // POST: SyllabusDates/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
       [ValidateInput(false)]
        public ActionResult Create([Bind(Include = "Id,Title,Class,School,From,To,Content")] SyllabusDate syllabusDate)
        {
            if (ModelState.IsValid)
            {
                syllabusDate.Id = Guid.NewGuid();
                
                db.SyllabusDates.Add(syllabusDate);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.Class = new SelectList(db.Classes, "Id", "RomanDisplay", syllabusDate.Class);
            ViewBag.School = new SelectList(db.Schools, "Id", "SchoolName", syllabusDate.School);
            return View(syllabusDate);
        }

        // GET: SyllabusDates/Edit/5
        public ActionResult Edit(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SyllabusDate syllabusDate = db.SyllabusDates.Find(id);
            if (syllabusDate == null)
            {
                return HttpNotFound();
            }
            ViewBag.Class = new SelectList(db.Classes, "Id", "RomanDisplay",syllabusDate.Class);
            ViewBag.School = new SelectList(db.Schools, "Id", "SchoolName",syllabusDate.School);
            return View(syllabusDate);
        }

        // POST: SyllabusDates/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Edit([Bind(Include = "Id,Title,Class,School,From,To,Content")] SyllabusDate syllabusDate)
        {
            if (ModelState.IsValid)
            {
                db.Entry(syllabusDate).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.Class = new SelectList(db.Classes, "Id", "RomanDisplay", syllabusDate.Class);
            ViewBag.School = new SelectList(db.Schools, "Id", "SchoolName", syllabusDate.School);
            return View(syllabusDate);
        }
        //private IEnumerable<Object> ClassList()
        //{
        //    foreach (var item in db.Classes)
        //    {
        //        yield return new { Value = item.Id.ToString(), Name = item.RomanDisplay };
        //    }
        //}
        // GET: SyllabusDates/Delete/5
        public ActionResult Delete(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SyllabusDate syllabusDate = db.SyllabusDates.Find(id);
            if (syllabusDate == null)
            {
                return HttpNotFound();
            }
            return View(syllabusDate);
        }

        // POST: SyllabusDates/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(Guid id)
        {
            //SyllabusDate syllabusDate = db.SyllabusDates.Find(id);
            var quizs = db.Quizes.Where(i => i.SyllabusId == id).ToList();
            foreach(var i in quizs)
            {
                i.Questions.Clear();
            }
            db.Quizes.RemoveRange(quizs);
            db.SaveChanges();
            SyllabusDate syllabusDate = db.SyllabusDates.Find(id);
            db.SyllabusDates.Remove(syllabusDate);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        public ActionResult CreateQuiz(Guid? Id)
        {
            ViewBag.Id = Id ?? Guid.Empty;
            return View();
        }

        public ActionResult Quiz(Guid? sid,int page=1,int size=10,string search="")
        {
            ViewBag.SyllabusId = sid;
            IQueryable<Quiz> List;
            if (!string.IsNullOrEmpty(search))
                List = db.Quizes.Where(i => i.Name.Contains(search) || i.Syllabus.Title.Contains(search));
            else
                List = db.Quizes.Where(i => i.SyllabusId == sid);
            ViewBag.Pager = Pagers.Items(List.Count()).PerPage(size).Move(page).Segment(20).Center();
            return View(List.OrderBy(i=>i.Id).Skip((page-1)*size).Take(size).ToList());
        }

        [HttpPost]
        public ActionResult CreateQuiz(QuizEntryVm Question,int? id)
        {
            ViewBag.Quizid = id;
            var p = new Quiz
            {
                Class = Question.ClassId.ToString(),
                Subject = Question.Subject,
                Details = Question.Details,
                Id = Guid.NewGuid(),
                Questions = new List<Questions>(),
                Name = Question.Title,
                NoOfQuestion = Question.Questions.Count(),
                On = DateTime.UtcNow,
                School = Question.SchoolId.ToString()
            };
            if (Question.SyllabusId != Guid.Empty)
            {
                p.SyllabusId = Question.SyllabusId;
            }

            
            db.Quizes.Add(p);
            db.SaveChanges();
            foreach(var i in Question.Questions)
            {
                var ip = db.Questions.Find(i.Id);
                p.Questions.Add(ip);
                //ip.Quiz.Add(p);
                db.Entry(p).State = EntityState.Modified;
                db.SaveChanges();
            }
            NotificationManagerRepo repo = new NotificationManagerRepo();
            var typeFeed = Model.Notifications.ModType.WRKSHT;

            var Nf = new Notification
            {
                Id = Guid.NewGuid().ToString(),
                Date = DateTime.UtcNow.AddDays(10),
                Group = p.Class,
                Message = $"New Work Sheet has been added",
                Title = "Work Book",
                PostId = p.Id.ToString(),
                Module = typeFeed,
                ImageUrl = "/static/img/feedIcon/ic_my_workbook.png",
                Size = true,
                Link = $"/POST/{typeFeed}/{p.Id}"

            };
            //db.Notification.Add(Nf);
            repo.AddNotification(Nf);
            return Json(new { data = Question, Measage = "Data Saved" });

        }
        public ActionResult DeleteQuiz(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Quiz quiz = db.Quizes.Find(id);
            if (quiz == null)
            {
                return HttpNotFound();
            }
            return View(quiz);
        }

        // POST: SyllabusDates/Delete/5
        [HttpPost, ActionName("DeleteQuiz")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteQuizConfirmed(Guid id)
        {

            Quiz quiz = db.Quizes.Include(i => i.Questions).FirstOrDefault(i => i.Id == id);
            db.Quizes.Remove(quiz);
            db.SaveChanges();
            return RedirectToAction("Quiz", new { sid=quiz.SyllabusId});
        }

    }
}

Scoolfirst.Admin/Views/SyllabusDates/Create.cshtml
@model Scoolfirst.Model.WorkBook.SyllabusDate

@{
    ViewBag.Title = "Create";
}

@UIHelper.Header("Syllabus")
<section class="content">
    <div class="row">
        <div class="col-xs-12">
            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                <div class="box box-primary">
                    <div class="box-header">
                        <h3>Create</h3>
                    </div>
                    <!-- /.box-header -->
                    <!-- form start -->

                    <div class="box-body">
                        <div class="form-group">
                            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = " " })
                            @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.Class, htmlAttributes: new { @class = " " })
                            @Html.DropDownList("Class",null, new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.Class, "", new { @class = "text-danger" })
                        </div>
                        <div class="form-group">
                            @Html.LabelFor(model => model.School, htmlAttributes: new { @class = " " })
                            @Html.DropDownList("School", null, new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.School, "", new { @class = "text-danger" })
                        </div>
                        
                        <div class="form-group">
                            <label for="dtp_input1" class=" control-label">Date From</label>
                            <div class="input-group date form_datetime "  data-date-format="dd MM yyyy  HH:ii p" data-link-field="dtp_input1">
                                <input class="form-control" type="text" value="" name="From">
                                <span class="input-group-addon"><span class="glyphicon glyphicon-remove"></span></span>
                                <span class="input-group-addon"><span class="glyphicon glyphicon-th"></span></span>
                            </div>

                        </div>
                        <div class="form-group">
                            <label for="dtp_input1" class=" control-label">Date To</label>
                            <div class="input-group date form_datetime "  data-date-format="dd MM yyyy  HH:ii p" data-link-field="dtp_input1">
                                <input class="form-control" type="text" value="" name="To">
                                <span class="input-group-addon"><span class="glyphicon glyphicon-remove"></span></span>
                                <span class="input-group-addon"><span class="glyphicon glyphicon-th"></span></span>
                            </div>

                        </div>
                        <div class="form-group">
                            @Html.LabelFor(model => model.Content, htmlAttributes: new { @class = " " })
                            @Html.TextAreaFor(model => model.Content,new { @class = "richeditor" })
                            @Html.ValidationMessageFor(model => model.Content, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <!-- /.box-body -->

                    <div class="box-footer">
                        <button type="submit" class="btn btn-success pull-right">Save Changes</button>
                        <a href="~/SyllabusDates/index" class="btn btn-danger pull-right" style="margin-right:5px"><i class="fa fa-remove"></i></a>
                    </div>

                </div>
            }
        </div>
    </div>
</section>

@section Scripts {
<link href="~/Content/DatePicker/bootstrap-datetimepicker.min.css" rel="stylesheet" />
    @Scripts.Render("~/bundles/jqueryval")
  <script src="~/Content/tinymce/js/tinymce/tinymce.min.js"></script>
<script src="/tinymce/settings"></script>
<script>tinymce.init({ selector:'.richeditor' });</script>
<script src="~/Content/DatePicker/bootstrap-datetimepicker.min.js"></script>
<script src="~/Content/DatePicker/locales/bootstrap-datetimepicker.fr.js"></script>

<script type="text/javascript">
    $(function () {
      
        $('.form_datetime').datetimepicker({
            //language:  'fr',
            weekStart: 1,
            todayBtn: 1,
            autoclose: 1,
            todayHighlight: 1,
            startView: 2,
            forceParse: 0,
            //showMeridian: 1
        });
    });

</script>

}

Scoolfirst.Admin/Views/SyllabusDates/CreateQuiz.cshtml
@{
    ViewBag.Title = "CreateQuiz";
}

@UIHelper.Header("Add A Quiz")

<input type="hidden" name="id" value="@ViewBag.Quizid"/>
<form name="formValid" >
    <section class="content" ng-controller="QuicCntrl" ng-init="QuizModel.SyllabusId='@(ViewBag.Id)'">
        <div class="row">
            <div class="col-md-12">
<div class="box box-primary">
    <div class="box-header">
        <h4>Fill In the required field</h4>
    </div>
    <div class="box-body">
        <div class="form-group">
            Title :<input type="text" name="Title" ng-model="QuizModel.Title" class="form-control " required />
            {{formValid.Title.$valid}}
        </div>
        <div class="form-group">
            Details :<textarea name="Details" rows="6" class="form-control" required ng-model="QuizModel.Details"></textarea>
        </div>
        <div class="form-group">
            <div class="col-md-4">
                Class:

                <select class="form-control" ng-model="QuizModel.ClassId" ng-change="changequestion()"
                        ng-options="clas.Id as clas.Name for clas in Classes" required>
                    <option value=''>Select Class</option>
                    @*<option ng-repeat="clas in Classes" value={{clas.Id}}>{{clas.Name}} </option>*@

                </select>
            </div>
            <div class="col-md-4">
                School:
                <select class="form-control" ng-model="QuizModel.SchoolId" ng-change="changequestion()" ng-options="school.Id as school.Name for school in Schools" required>
                    <option value=''>Select School</option>
                    @*<option ng-repeat="school in Schools" value={{school.Id}}>{{school.Name}}</option>*@
                </select>
            </div>

            <div class="col-md-4">
                Subject:
                <select class="form-control" ng-model="QuizModel.Subject" ng-change="changequestion()" ng-options="subject.SubjectName as subject.SubjectName for subject in Subjects" required>
                    <option value=''>Select Subject</option>
                    @*<option ng-repeat="subject in Subjects" value={{subject.SubjectName}}>{{subject.SubjectName}}</option>*@

                </select>
            </div>

        </div>
        <div class="form-group col-md-12">
            <div class="row">
                <div class="col-md-6">

                   
                       
                        <div  class="panel panel-default" heading="({{qgrp[0].Book}} -> {{qgrp[0].Chapter}} [{{qgrp.length}}])" ng-repeat="qgrp in Questions | groupBy: 'Chapter'" template-url="group-template.html">
                           <div class="box-header with-border">
                               <h4 class="box-title">
                                   <a data-toggle="collapse" data-parent="#accordion" href="#Chapter{{$index}}" aria-expanded="false" class="">
                                       ({{qgrp[0].Book}} -> {{qgrp[0].Chapter}} [{{qgrp.length}}])
                                   </a>
                               </h4>
                           </div>
                            <div id="Chapter{{$index}}" class="panel-collapse collapse in" aria-expanded="false">
                                <ul class="list-group">
                                    <li ng-repeat="quest in qgrp" class="list-group-item">
                                        <div class="col-lg-1">{{$index+1}}</div>
                                        <div ng-bind-html="quest.Title" class="col-lg-10">

                                        </div>
                                        <button ng-click="Add(quest,$index)" class="pull-right btn btn-success"><i class="glyphicon glyphicon-check"></i></button>
                                        <div class="clearfix"></div>
                                    </li>
                                </ul>
                            </div>
                             
                        </div>
                        
                  



                    @*<ul class="list-group" ng-repeat="qgrp in Questions | groupBy: 'Chapter'">
                        <li class="list-group-item-heading list-group-item list-group-item-danger">
                          ({{qgrp[0].Book}} -> {{qgrp[0].Chapter}} [{{qgrp.length}}])
                        </li>
                        <li ng-repeat="quest in qgrp" class="list-group-item">
                            <div class="col-lg-1">{{$index+1}}</div>
                            <div ng-bind-html="quest.Title" class="col-lg-10">

                            </div>
                            <button ng-click="Add(quest,$index)" class="pull-right btn btn-success"><i class="glyphicon glyphicon-check"></i></button>
                            <div class="clearfix"></div>
                        </li>

                    </ul>*@
                </div>
                <div class="col-md-6">
                    <ul class="list-group">
                        <li class="list-group-item list-group-item-heading list-group-item-danger ">
                            Selected Questions [{{QuizModel.Questions.length}}]
                        </li>
                        <li ng-repeat="sel in QuizModel.Questions" class="list-group-item list-group-item-info">
                            <div class="col-lg-1">{{$index+1}}</div>
                            <div ng-bind-html="sel.Title" class="col-lg-10">

                            </div>

                            <button ng-click="Remove(sel,$index)" class="pull-right btn btn-danger"><i class="glyphicon glyphicon-remove"></i></button>
                            <div class="clearfix"></div>

                        </li>
                    </ul>
                </div>

            </div>
          
          

        </div>
    </div>

    <div class="box-footer">
        <button class="btn btn-success pull-right" ng-click="Save()">Save</button>
    </div>

</div>
            </div>
        </div>

    </section>






  


</form>

@section scripts{
    
<script src="~/Scripts/Quiz/Quiz.js"></script>
    <script type="text/ng-template" id="group-template.html">
    <div class="panel panel-default">
        <div class="panel-heading">
            <h4 class="panel-title" style="color:#fa39c3">
                <a href tabindex="0" class="accordion-toggle" ng-click="toggleOpen()" uib-accordion-transclude="heading">
                    <span uib-accordion-header ng-class="{'text-muted': isDisabled}">
                        {{heading}}
                    </span>
                </a>
            </h4>
        </div>
        <div class="panel-collapse collapse" uib-collapse="!isOpen">
            <div class="panel-body" style="text-align: right" ng-transclude></div>
        </div>
    </div>
</script>
    }

Scoolfirst.Admin/Views/SyllabusDates/Delete.cshtml
@model Scoolfirst.Model.WorkBook.SyllabusDate

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>SyllabusDate</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Class)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Class)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.From)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.From)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.To)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.To)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Content)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Content)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Scoolfirst.Admin/Views/SyllabusDates/Details.cshtml
@model Scoolfirst.Model.WorkBook.SyllabusDate

@{
    ViewBag.Title = "Details";
}

@UIHelper.Header("Syllabus")
<section class="content">
    <div class="row">
        <div class="col-md-12">
            <div class="box box-solid">
                <div class="box-header with-border">
                    <i class="fa fa-text-width"></i>

                    <h3 class="box-title">Details Of Syllabus</h3>
                </div>
                <!-- /.box-header -->
                <div class="box-body">
                    <dl>
                        <dt>Title</dt>
                        <dd>@Html.Raw(Model.Title)</dd>
                        <dt>Class</dt>
                        <dd>@Html.Raw(Model.Class)</dd>
                        <dt>From</dt>
                        <dd>@Model.From</dd>
                        <dt>To</dt>
                        <dd>@Model.To</dd>
                        <dt>Content</dt>
                        <dd>@Html.Raw(Model.Content)</dd>
                       

                    </dl>
                </div>
                <!-- /.box-body -->
                <div class="box-footer">
                    <a href="@Url.Action("Edit", "SyllabusDates", new { id = Model.Id })" class="btn btn-success pull-right"><i class="fa fa-edit"></i></a>

                    <a href="@Url.Action("Index","SyllabusDates")" class="btn btn-danger "><i class="fa fa-remove"></i></a>

                </div>
            </div>
            <!-- /.box -->
        </div>
    </div>
</section>

Scoolfirst.Admin/Views/SyllabusDates/Index.cshtml
@model IEnumerable<Scoolfirst.Model.WorkBook.SyllabusDate>

@{
    ViewBag.Title = "Index";
   // var p = Model.First().School
}

@UIHelper.Header("Syllabus",null,"List Of All Syllabus")
<section class="content">
    <div class="row">

        <div class="col-xs-12">

            <div class="box box-primary">

                <div class="box-header">
                    @UIHelper.Search(Url.Action("Create", "SyllabusDates"), "")
                </div>
                <div class="box-body">
                    <table class="table table-bordered  table-condensed table-striped table-vmiddle ">
                        <thead>
                            <tr>

                                <th>
                                    @Html.DisplayNameFor(model => model.Title)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.Class)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.School)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.From)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.To)
                                </th>
                                
                                <th>Action</th>
                            </tr>
                        </thead>
                        @foreach (var item in Model)
                        {
                            <tbody>
                                <tr>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Title)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Class)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.School)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.From)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.To)
                                    </td>
                                    
                                    <td class="btn-group btn-group-sm" width="160px">
                                        <a href="@Url.Action("Edit",  new { id = item.Id })" class="btn btn-sm btn-success"><i class="fa fa-edit"></i></a>
                                        <a href="@Url.Action("Details",  new { id = item.Id })" class="btn btn-sm btn-info"><i class="fa fa-eye"></i></a>
                                        <a href="@Url.Action("Delete",  new { id = item.Id })" class="btn btn-sm btn-danger"><i class="fa fa-trash"></i></a>
                                        <a href="@Url.Action("CreateQuiz","SyllabusDates", new { id=item.Id})" class="btn btn-sm btn-primary"><i class="fa fa-clipboard">Add Quiz</i></a>
                                        <a href="@Url.Action("Quiz","SyllabusDates", new { sid=item.Id})" class="btn btn-sm bg-navy"><i class="fa fa-list">View Quiz</i></a>
                                    </td>
                                </tr>
                            </tbody>
                        }

                    </table>
                   
                    <div class="box-footer">
                        @Pager.Page("/SyllabusDates/Index")
                    </div>
                </div>
            </div>

        </div>
    </div>
</section>

Scoolfirst.Admin/Views/SyllabusDates/Quiz.cshtml
@model IEnumerable<Scoolfirst.Model.WorkBook.Quiz>

@{
    ViewBag.Title = "Quiz";
}
<input type="hidden" name="SyllabusId" value="@ViewBag.SyllabusId"/>
@UIHelper.Header("Quiz",null,"List Of All Quiz Question")
<section class="content">
    <div class="row">

        <div class="col-xs-12">

            <div class="box box-primary">

                <div class="box-header">
                    @UIHelper.Search(Url.Action("CreateQuiz", "SyllabusDates", new { id= ViewBag.SyllabusId }), "")
                </div>
                <div class="box-body">
                    <table class="table table-bordered  table-condensed table-striped table-vmiddle ">
                        <thead>
                            <tr>
                                <th>
                                    @Html.DisplayNameFor(model => model.Syllabus.Title)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.Name)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.Subject)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.Details)
                                </th>
                                <th>
                                    No Of Question
                                </th>
                              <th>
                                  Action
                              </th>
                            </tr>
                        </thead>
                        @foreach (var item in Model)
                        {
                            <tbody>
                                <tr>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Syllabus.Title)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Name)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Subject)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Details)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.NoOfQuestion)
                                    </td>
                                   <td>
                                       <a href="@Url.Action("DeleteQuiz",  new { id = item.Id })" class="btn btn-sm btn-danger"><i class="fa fa-trash"></i></a>

                                   </td>
                                    
    </tr>
                            </tbody>
                        }

                    </table>

                    <div class="box-footer">
                        @Pager.Page("/Quiz/Index")
                    </div>
                </div>
            </div>

        </div>
    </div>
</section>